#fuckapp configuration file

port: 8080
serverHost: 'http://localhost'
env: "dev"
dbdriver: "mysql"
basic_http_authorization_user: "quepasa"
basic_http_authorization_password: "calabasa"
google_key: "AIzaSyA90gKIioGv6FE-mfpxcGwjWS_DBTOUMmg"

################################################################################
# Database settings
################################################################################

# MySql database info
db:
    dev: 
        mysql:
            driver: "mysql"
            username: "root"
            database: "fuckapp"
            password: "fuckapp"
            host: "localhost"
            dialect: "mysql"
            DBHost: "localhost"
        mongo:
            DBHost: "localhost"
    test: 
        mysql:
            driver: "mysql"
            username: "root"
            database: "fuckapp_test"
            password: "fuckapp"
            host: "localhost"
            dialect: "mysql"
            DBHost: "localhost"
        mongo:
            DBHost: "localhost"
        storage:
            uploads_path: "uploads-test/"

################################################################################
# Logging options
################################################################################

# Log file path
log_file: './fuckapp_log.txt'

# Log level to use, omits lower log levels
# Levels, lowest to highest: silly, debug, verbose, info, warn, error
# default = 'info'
log_level: 'silly'

################################################################################
# Storage options
################################################################################

storage:
    dev:
        uploads_path: "uploads/"
    test:
        uploads_path: "uploads-test/"